config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
    post 'shipping_destinations', to: 'users/registrations#create_shipping_destination'
    get 'shipping_destinations', to: 'users/registrations#new_shipping_destination'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"

  resources :users, only: :show do
    get 'logout' => "users#logout"
  end

  # resources :items, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :items, except: :index do
    collection do
      get 'pay'
      get 'categoryChildren'
      get 'categoryGrandChildren'
    end
    member do
      get 'categoryChildren'
      get 'categoryGrandChildren'
    end
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end  
  end

  resources :card, only: [:new, :show, :index] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @items = Item.all.order(created_at: "DESC").limit(3)
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/_footer.html.haml
.footer__wrapper
  %ul.footer__contents
    %li.footer__content
      %h2.footer__item__title FURIMAについて
      %ul
        %li
          = link_to root_path, class: "footer__item" do
            会社概要（運営会社）
        %li
          = link_to root_path, class: "footer__item" do
            プライバシーポリシー
        %li
          = link_to root_path, class: "footer__item" do
            FURIMA利用規約
        %li
          = link_to root_path, class: "footer__item" do
            ポイントに関する特約
    %li.footer__content
      %h2.footer__item__title FURIMAを見る
      %ul
        %li
          = link_to root_path, class: "footer__item" do
            カテゴリー一覧
        %li
          = link_to root_path, class: "footer__item" do
            ブランド一覧
    %li.footer__content
      %h2.footer__item__title ヘルプ&ガイド
      %ul
        %li
          = link_to root_path, class: "footer__item" do
            FURIMAガイド
        %li
          = link_to root_path, class: "footer__item" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to root_path, class: "footer__item" do
            お知らせ
  .footer__logo
    = link_to image_tag 'logo-white.png', class: "footer__logo--white"
    %p.footer__logo__name © FURIMA

app/views/top/_header.html.haml
.header
  .header__inner
    .header__inner__main
      .header__inner__main__icon
        = link_to image_tag('logo.png', size: "140x41"), root_path
      .header__inner__main__search-box
        = form_tag('#', method: :get) do
          %input.header__inner__main__search-box--input{placeholder: "キーワードから探す"}
          %button.header__inner__main__search-box__btn-search{type: "submit"}
            = image_tag 'icon-search 1.png', size: "20x20"
            
    .header__inner__nav
      %ul.listsLeft
        %li.listsLeft__item.listsLeft__item--first
          = link_to root_path do
            カテゴリー
        %li.listsLeft__item
          = link_to root_path do
            ブランド

      %ul.listsRight
        -if user_signed_in?
          %li.listsRight__item.listsRight__item--mypage
            = link_to "/users/#{current_user.id}",id:'catBtn' do
              マイページ
          %li.listsRight__item.listsRight__item--new
            = link_to  destroy_user_session_path, method: :delete,id:'catBtn' do
              ログアウト
        -else
          %li.listsRight__item.listsRight__item--login
            = link_to user_session_path,id:'catBtn' do
              ログイン
            %ul.headder__nav-listsright-brandsPulldown
          %li.listsRight__item.listsRight__item--new
            = link_to  new_user_registration_path,id:'catBtn' do
              新規会員登録

app/views/top/_section1.html.haml
.main
  %section.main__mainVisual
    .main__mainVisual__content
      %h2.main__mainVisual__content__subtitle
        %br
        人生を変えるフリマアプリ
      %p.main__mainVisual__content__text
        %br
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです 
      .main__mainVisual__content__btn
        .aBtn
          = link_to image_tag('apple.jpeg'), root_path
        .gBtn(href="#")
          = link_to image_tag('google_logo.png'), root_path

app/views/top/_section2.html.haml
.main
  %section.main__topIntroduction
    %h2.main__topIntroduction__subtitle
      FURIMAが選ばれる3つの理由
    %ul.main__topIntroduction__lists
      %li.list
        .list__pict
          %span.number 1
          = image_tag 'pict-reason-01.jpg', size: "306x306"
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる!
      %li.list
        .list__pict
          %span.number 2
          = image_tag 'pict-reason-02.jpg', size: "306x306"
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ!
        %li.list.list--last
          .list__pict
            %span.number 3
            = image_tag 'pict-reason-03.jpg', size: "306x306"
          %h3.list__text
            手数料
            %span 業界最安
          %p.list__description
            最大3%でお得に出品&購入!

app/views/top/_section3.html.haml
.section__feature
  .section__feature__contents
    %h2.section__feature__title FURIMAの特徴
    .section__feature__content
      .section__feature__item
        = image_tag 'icon-01.png', class: "section__feature__item__image"
        %h3 簡単に売り買いできる
        %p スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .section__feature__item
        = image_tag 'icon-03.png', class: "section__feature__item__image"
        %h3 売上金は即日振込みに対応
        %p 午前９時までに振込を依頼いただければ、翌日に指定の口座に入金致します！
      .section__feature__item
        = image_tag 'icon-04.png', class: "section__feature__item__image"
        %h3 様々な支払いに対応
        %p お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/top/_section4.html.haml
.section__pickup
  %h2.section__pickup__title ピックアップカテゴリー
  .new__item__contents
    = link_to root_path, class: "new__item__index" do
      新規投稿商品
    .new__item__lists
      - @items.each do |item|
        .new__item__list
          = link_to item_path(item.id) do
            =image_tag item.images.first.url.url ,class: "new__item__image"
              -# 売り切れた商品にはsoldを表示する条件分岐 
              -if item.trading_status == "完売"
              .new__item__image__sold
                .new__item__image__sold__inner
                  SOLD
            .new__item__info
              %h3.new__item__name=item.name
              .new__item__value
                %ul
                  %li=item.price
                  %h4 円
                  %li
                    %icon.fa.fa-star
                      0
                %p (税込)
      
.section__pickup
  %h2.section__pickup__title ピックアップブランド
  .new__item__contents
    = link_to root_path, class: "new__item__index" do
      アーカイバ
    .new__item__lists
      .new__item__list
        = link_to root_path do
          =image_tag 'icon-03.png',class: "new__item__image"
          .new__item__info
            %h3.new__item__name Product
            .new__item__value
              %ul
                %li 30000円
                %li
                  %icon.fa.fa-star
                    0
              %p (税込)
      .new__item__list
        = link_to root_path do
          =image_tag 'icon-03.png',class: "new__item__image"
          .new__item__info
            %h3.new__item__name Product
            .new__item__value
              %ul
                %li 30000円
                %li
                  %icon.fa.fa-star
                    0
              %p (税込)
      .new__item__list
        = link_to root_path do
          =image_tag 'icon-03.png',class: "new__item__image"
          .new__item__info
            %h3.new__item__name Product
            .new__item__value
              %ul
                %li 30000円
                %li
                  %icon.fa.fa-star
                    0
              %p (税込)
  

app/views/top/_section5.html.haml
.bottom__banner
  .bottom__banner__contents
    %h2 だれでもかんたん、人生をかえるフリマアプリ
    %h3.bottom__banner__title__sub 今すぐ無料ダウンロード！
    .store__logo
      =image_tag 'apple.jpeg',class: "store__image"
      =image_tag 'google_logo.png',class: "store__image"
    

app/views/top/index.html.haml
.wrapper
  .header
    = render partial: 'header'
  .main__section1  
    = render partial: 'section1'
  .main__section2
    = render partial: 'section2'
  .main__section3
    = render partial: 'section3'
  .main__section4
    = render partial: 'section4'
  .main__section5
    = render partial: 'section5'
  .footer
    = render partial: 'footer'
  = link_to new_item_path, class: "purchage__send" do
    %p 出品する
    =image_tag 'icon_camera.png',class: "camera__image"