config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
    post 'shipping_destinations', to: 'users/registrations#create_shipping_destination'
    get 'shipping_destinations', to: 'users/registrations#new_shipping_destination'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"

  resources :users, only: :show do
    get 'logout' => "users#logout"
  end

  # resources :items, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :items, except: :index do
    collection do
      get 'pay'
      get 'categoryChildren'
      get 'categoryGrandChildren'
    end
    member do
      get 'categoryChildren'
      get 'categoryGrandChildren'
    end
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end  
  end

  resources :card, only: [:new, :show, :index] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  before_action :set_item
  require 'payjp'

  def index
    @shipping_destination = ShippingDestination.find_by(user_id: current_user.id)
    shipping_prefecture = ShippingPrefecture.find(@item.shipping_prefecture_id)
    @shipping_prefecture = shipping_prefecture.name
    @card = Card.where(user_id: current_user.id).first
    if @card.blank?
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    :amount => @item.price,
    :customer => card.customer_id,
    :currency => 'jpy',
  )
    redirect_to action: 'done'
  end

  def done
    @item.update(trading_status: "売り切れ")
  end

  private
  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/purchase/done.html.haml
.doneWrapper
  .doneWrapper__content
    .doneWrapper__content__message
      購入が完了しました！
    .doneWrapper__content__link
      = link_to "トップページに戻る", root_path, class: "doneWrapper__content__link__btn"

app/views/purchase/index.html.haml
.main__purchage
  .main__purchage__wrapper
    .section__purchage.main__top
      %h2.main__top__title 購入内容の確認
    .section__purchage.main__product
      .product__content
        =image_tag @item.images.first.url.url,class: "store__image"
        .product__purchage
          %p.product__title 
            = @item.name
          %p.product__price 
            ¥
            = @item.price
    .section__purchage.main__payment
      .payment
        %span.payment__title 支払い金額
        %span.payment__amount 
          ¥
          = @item.price
      .point
        %label.purchage__box{:for => "point__checkbox"}
          %input.point__checkbox{:name => "point", :type => "checkbox", :value => "1"}/
          ポイントを使用（所持ポイント:P〇〇）
    .section__purchage
      .payment__method
        %h3.payment__title 支払い方法
      .payment__info
        %br
        クレジットカード
        %br
        = "**** **** **** " + @default_card_information.last4
        %br
        有効期限
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year

    .section__purchage
      .payment__method
        %h3.payment__title 配送先
      .payment__info
        .piAddress__postCode
          = "〒" + "#{@shipping_destination.post_code.to_s.insert(3, "-")}"
        .piAddress__destination
          = "#{@shipping_prefecture}" + "#{@shipping_destination.city}" + "#{@shipping_destination.address}"
        .piAddress__name
          = @shipping_destination.building
    .section__purchage.purchase
      %div
        %p.purchase__text
          郵便局/コンビニ受取をご希望の方は、購入後に
          %b> 取引画面
          から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
      - if @card.blank?
        .purchase__contents--button--message
          クレジットカードが登録されていません
      - else
        %button.btn.purchase
          = link_to '購入する', pay_item_purchase_index_path(id: @item.id), method: :post