config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
    post 'shipping_destinations', to: 'users/registrations#create_shipping_destination'
    get 'shipping_destinations', to: 'users/registrations#new_shipping_destination'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"

  resources :users, only: :show do
    get 'logout' => "users#logout"
  end

  # resources :items, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :items, except: :index do
    collection do
      get 'pay'
      get 'categoryChildren'
      get 'categoryGrandChildren'
    end
    member do
      get 'categoryChildren'
      get 'categoryGrandChildren'
    end
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end  
  end

  resources :card, only: [:new, :show, :index] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name,length: { in: 1..40 }
  validates :introduction,length: { in: 1..1000 }
  validates :price, numericality: { less_than_or_equal_to: 9999999, greater_than_or_equal_to: 300 }
  validates :category_id, :item_condition_id, :shipping_day_id, :shipping_prefecture_id, :user_id, :name, :introduction, :postage_payer_id, :price, presence: true
  validates :images, presence: true
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :item_condition
  belongs_to_active_hash :postage_payer
  belongs_to_active_hash :shipping_prefecture
  belongs_to_active_hash :shipping_day
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_parents, only: [:new, :create, :show, :edit, :update]

  def index
    @items = Item.all.order(created_at: "DESC").limit(3)
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def categoryChildren
    @categoryChildren = Category.find(params[:selectedCategory]).children
  end

  def categoryGrandChildren
    @categoryGrandChildren = Category.find(params[:selectedCategory]).children
  end

  def edit 
    unless @item.user.id == current_user.id 
      redirect_to posts_path
      flash[:alert] = "権限がありません"
    end
  end

  def update
    @item.update(item_params)
    if @item.save
      flash[:notice] = "編集完了しました"
      redirect_to root_path
    else
      flash.now[:alert] = "編集に失敗しました"
      render ("items/edit")
    end
  end

  def pay
    
  end


  def create
    @item = Item.create(item_params)
    if @item.save
      flash[:notice] = "投稿完了しました"
      redirect_to root_path
    else
      flash.now[:alert] = "投稿に失敗しました"
      render ("items/new")
    end
  end

  def destroy
    if current_user.id == @item.user.id && @item.destroy
      flash[:notice] = "削除しました"
      redirect_to root_path
    else
      flash.now[:alert] = "削除に失敗しました"
      render ("items/show")
    end
  end



  def show

    # user = User.all
    @user = @item.user.nickname

    @category = Category.find(@item.category_id)
      
    condition = ItemCondition.find(@item.item_condition_id)
    @condition = condition.name
    
    postage_payer =  PostagePayer.find(@item.postage_payer_id)
    @postage_payer = postage_payer.name
    
    shipping_day = ShippingDay.find(@item.shipping_day_id)
    @shipping_day = shipping_day.name

    
    shipping_prefecture = ShippingPrefecture.find(@item.shipping_prefecture_id)
    @shipping_prefecture = shipping_prefecture.name
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :category_id, :brand, :item_condition_id, :postage_payer_id, :shipping_prefecture_id, :shipping_day_id, :price, :trading_status, images_attributes: [:url, :_destroy, :id]).merge(user_id: current_user.id)
  end

  #ログインしていなくても一覧表示する
  def move_to_index
    unless user_signed_in?
    flash.now[:alert] = "ログインをしてください"
    redirect_to root_path
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_show_item_main-content.html.haml
%section.item-box-container
  %h1.item-name<
    = @item.name
  .item-main-content
    .item-photo
      .item-photo__main
        = image_tag @item.images[0].url.url, class: "item-photo__main__parent"
      .item-photo__sub
        - @item.images[1..-1].each do |image|
          = image_tag image.url.url, class:'item-photo__sub__children'
    %table.item-detail-table
      %tr
        %th 出品者
        %td 
          = @user
      %tr
        %th カテゴリー
        %td
          - @parents.each do |parent|
            -if @item.category_id == parent.id
              = link_to '#' do
                = parent.name
                %br
            - parent.children.each do |child|
              -if @item.category_id == child.id
                = link_to '#' do
                  = parent.name
                  %br
                = link_to '#' do
                  >
                  = child.name
                  %br
              - child.children.each do |grandchild|
                -if @item.category_id == grandchild.id
                  = link_to '#' do
                    = parent.name
                  %br
                  = link_to '#' do
                    >
                    = child.name
                  %br
                  = link_to '#' do
                    >>
                    = grandchild.name
                  %br
      %tr
        %th ブランド
        %td 
          = @item.brand
      %tr
        %th 商品の状態
        %td 
          =  @condition
      %tr
        %th 配送料の負担
        %td 
          = @postage_payer
      %tr
        %th 発送元の地域
        %td 
          = @shipping_prefecture
      %tr
        %th 発送日の目安
        %td 
          = @shipping_day
  .item-price
    %span.item-price-bold= "¥#{@item.price.to_s(:delimited, delimiter: ',')}"
    %span.item-tax (税込み)
    %span.item-shipping-fee 送料込み
  -if user_signed_in?
    -if current_user.id == @item.user_id 
      = link_to '商品情報を編集する', edit_item_path(@item), class: "item-edit-btn"
      = link_to '削除する', item_path, class: "item-delete-btn", method: :delete
      -# = link_to '削除する', '#', class: "item-delete-btn"
    -elsif @item.trading_status != "販売中"
      .sell-btn 売り切れ
    -else
      = link_to '購入画面に進む', item_purchase_index_path(@item), class: "item-buy-btn"
    .item-introduction
      %p.item-introduction__content
        = @item.introduction
  -else
    = link_to "ログインする", user_session_path, class:"login-btn"
    = link_to "新規会員登録する", new_user_registration_path, class:"resist-btn"

app/views/items/edit.html.haml
.product-new
  .new__header
    =  link_to image_tag('logo.png', size: "140x41"), root_path
  = form_with model: @item, local: true do |f|
    .post__new__wrapper
      .main-content
        - @item.errors.full_messages.each do |message|
          .form-error
            = message
        .main-content__image
          #image-box
            %label.sell-content__image__label
              商品画像 
            %span.product-require
              必須
            .main-content__image__introduce
              最大5枚までアップロードできます
            .post__drop__box__container
              .prev-content
                - @item.images.each do |image|
                  .preview-box
                    .upper-box
                      = image_tag image.url.url, width: "112", height: "112", alt: "preview"
                    .lower-box
                      .update-box
                        %label.edit-btn 編集
                      .delete-box
                        %label.dalete-btn 削除
              .label-content
                = f.label :"images_attributes_#{@item.images.length}_url", class: "label-box", id: "label-box--#{@item.images.length}" do
                  %pre.label-box__text-visible クリックしてファイルをアップロード
              .hidden-content
                = f.fields_for :images do |i|
                  = i.file_field :url, class: "hidden-field"
                  = i.check_box:_destroy, class: "hidden-checkbox"

                
                - @item.images.length.upto(4) do |i|
                  %input{name: "item[images_attributes][#{i}][url]", id: "item_images_attributes_#{i}_url", class:"hidden-field", type:"file"}     
          = f.hidden_field :trading_status, value: "販売中"
        
        .sell-content
          .sell-content__name
            %label.sell-content__name__label
              商品名
              %span.product-name__require
                必須
          = f.text_field :name, placeholder: "40字まで"
          .sell-conent___introduce
            %label.sell-content__introduce__label
              商品の説明
              %span.product-introduce__require
                必須
            = f.text_area :introduction, placeholder: "商品の説明(必須1,000文字以内)"

        .detail-content
          .detail-content__category
            %label.detail-content__category__label
              カテゴリー
              %span.detail-content__category__require
                必須
          .selectBoxCategory
            #parentsWrapper
              = f.collection_select :category_id, @parents, :id, :name, { prompt: "選択してください" }, { id: "parentsCategory" }
          .detail-content__brand
            %label.detail-content__brand__label
              ブランド
              %span.detail-content__brand__require
                任意
          = f.text_field :brand, placeholder: "例) シャネル"
          .detail-content__condition
            %label.detail-content__condition__label
              商品の状態
              %span.detail-content__condition__require
                必須
          = f.collection_select :item_condition_id, ItemCondition.all, :id, :name, {prompt: "選択してください"}

        .delivery-content
          .delivery-content__chage
            %label.delivery-content__chage__label
              配送料の負担
              %span.delivery-content__chage__require
                必須
          = f.collection_select :postage_payer_id, PostagePayer.all, :id, :name, {prompt: "選択してください"}
          .delivery-content__area
            %label.delivery-content__area__label
              発送元の地域
              %span.delivery-content__area__require
                必須
          = f.collection_select :shipping_prefecture_id, ShippingPrefecture.all, :id, :name, {prompt: "選択してください"}
          .delivery-content__days
            %label.delivery-content__days__label
              発送までの日数
              %span.delivery-content__days__require
                必須
          = f.collection_select :shipping_day_id, ShippingDay.all, :id, :name, {prompt: "選択してください"}
        .price
          .price__left__content
            %label.price__left__left
              値段
              %span.price__left__require
                必須
          .price__right__content
            %label.price__mark
              ¥
            = f.number_field :price, placeholder: "0"
        .send 
          .send__btn
            = f.submit "出品する",onfocus: "this.blur();"
  .footer
    .footer__logo--white
      = image_tag 'logo-white.png', size: '140x41'
      %p.footer__logo__name © FURIMA

        

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.haml
.product-new
  .new__header
    =  link_to image_tag('logo.png', size: "140x41"), root_path
  = form_with model: @item, local: true do |f|
    .post__new__wrapper
      - if @item.errors.any?
        - @item.errors.full_messages.each do |message|
          .form-error
            = message
      .main-content
        .main-content__image
          #image-box
            %label.sell-content__image__label
              商品画像 
            %span.product-require
              必須
            .main-content__image__introduce
              最大5枚までアップロードできます
            .post__drop__box__container
              .prev-content
              .label-content
                %label{for: "item_images_attributes_0_url", class: "label-box", id: "label-box--0"}
                  %pre.label-box__text-visible クリックしてファイルをアップロード
              .hidden-content
                = f.fields_for :images do |image|
                  = image.file_field :url, class: 'hidden-field'
                  %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][url]", id: "item_images_attributes_1_url" }
                  %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][url]", id: "item_images_attributes_2_url" }
                  %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][url]", id: "item_images_attributes_3_url" }
                  %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][url]", id: "item_images_attributes_4_url" }          
          = f.hidden_field :trading_status, value: "販売中"
        
        .sell-content
          .sell-content__name
            %label.sell-content__name__label
              商品名
              %span.product-name__require
                必須
          = f.text_field :name, placeholder: "40字まで"
          .sell-conent___introduce
            %label.sell-content__introduce__label
              商品の説明
              %span.product-introduce__require
                必須
            = f.text_area :introduction, placeholder: "商品の説明(必須1,000文字以内)"

        .detail-content
          .detail-content__category
            %label.detail-content__category__label
              カテゴリー
              %span.detail-content__category__require
                必須
          .selectBoxCategory
            #parentsWrapper
              = f.collection_select :category_id, @parents, :id, :name, { prompt: "選択してください" }, { id: "parentsCategory" }
          .detail-content__brand
            %label.detail-content__brand__label
              ブランド
              %span.detail-content__brand__require
                任意
          = f.text_field :brand, placeholder: "例) シャネル"
          .detail-content__condition
            %label.detail-content__condition__label
              商品の状態
              %span.detail-content__condition__require
                必須
          = f.collection_select :item_condition_id, ItemCondition.all, :id, :name, {prompt: "選択してください"}

        .delivery-content
          .delivery-content__chage
            %label.delivery-content__chage__label
              配送料の負担
              %span.delivery-content__chage__require
                必須
          = f.collection_select :postage_payer_id, PostagePayer.all, :id, :name, {prompt: "選択してください"}
          .delivery-content__area
            %label.delivery-content__area__label
              発送元の地域
              %span.delivery-content__area__require
                必須
          = f.collection_select :shipping_prefecture_id, ShippingPrefecture.all, :id, :name, {prompt: "選択してください"}
          .delivery-content__days
            %label.delivery-content__days__label
              発送までの日数
              %span.delivery-content__days__require
                必須
          = f.collection_select :shipping_day_id, ShippingDay.all, :id, :name, {prompt: "選択してください"}
        .price
          .price__left__content
            %label.price__left__left
              値段
              %span.price__left__require
                必須
          .price__right__content
            %label.price__mark
              ¥
            = f.number_field :price, placeholder: "0"
        .send 
          .send__btn
            = f.submit "出品する",onfocus: "this.blur();"
  .footer
    .footer__logo--white
      = image_tag 'logo-white.png', size: '140x41'
      %p.footer__logo__name © FURIMA

        

app/views/items/pay.html.haml
.main__purchage
  .main__purchage__wrapper
    .section__purchage.main__top
      %h2.main__top__title 購入内容の確認
    .section__purchage.main__product
      .product__content
        =image_tag 'apple.jpeg',class: "store__image"
        .product__purchage
          %p.product__title 購入商品タイトル
          %p.product__price 購入商品料金¥○○
    .section__purchage.main__payment
      .payment
        %span.payment__title 支払い金額
        %span.payment__amount ¥100
      .point
        %label.purchage__box{:for => "point__checkbox"}
          %input.point__checkbox{:name => "point", :type => "checkbox", :value => "1"}/
          ポイントを使用（所持ポイント:P〇〇）
    .section__purchage
      .payment__method
        %h3.payment__title 支払い方法
        %a.change{:href => "#"} 変更する
      .payment__info
        %p クレジットカード
        %p *************1234
        %p 有効期限 01/23
        
    .section__purchage
      .payment__method
        %h3.payment__title 配送先
        %a.change{:href => "#"} 変更する
      .payment__info
        %p 〒123-4567
        %p 福岡県福岡市中央区メルカリ1-2-3
        %p メルカリオ
    .section__purchage.purchase
      %div
        %p.purchase__text
          郵便局/コンビニ受取をご希望の方は、購入後に
          %b> 取引画面
          から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
      %button.btn.purchase 購入する

app/views/items/show.html.haml
.header
  = render partial: 'top/header'
.wrapper
  = render partial: 'items/show_item_main-content'
.footer
  = render partial: 'top/footer'